name:                fastlinkedlist
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/fastlinkedlist#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - vector
  - c-storable-deriving
  - data-default
  - deepseq
  - doctest
  - extra
  - mtl
  - transformers

tests:
  test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fastlinkedlist
    - doctest

library:
  exposed-modules:
     - Data.OffHeapVector
     - Data.FastStack
     - Data.ArrayLinkedList.DLList
     - Data.ArrayLinkedList.DLList.IteratorDirection
     - Data.ArrayLinkedList.DLList.Ix
     - Data.ArrayLinkedList.DLList.Mutable
  source-dirs: lib
